---

- name: Include os-specific variables
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Copy public keys for ec2-user from control machine to instances
  authorized_key: user={{ app_code_user }}
                  key="{{ lookup('file', item) }}"
  with_fileglob:
    - ~/.ssh/*.pub

